name: CI/CD to AKS using Kubeconfig Secret

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: jayyy48/dotnet-mongo-crud
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4   # bump to latest version

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:$TAG .

    - name: Push Docker Image
      run: docker push $IMAGE_NAME:$TAG

    - name: Setup kubeconfig from secret
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to AKS
      run: |
        kubectl create ns webapps --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f dotnet-mongo-app.yaml -n webapps
